## Get all items
GET http://localhost:3000/items

###

## Get single item
GET http://localhost:3000/items/62c1e45811fe94021c589ace

###

## Create item
POST http://localhost:3000/items
Content-Type: application/json

{
    "name": "saks",
    "color": "#666"
}

###

## Update item
PATCH http://localhost:3000/items/62c1e568a94c5762e78eacb0
Content-Type: application/json

{
    "name": "kniv",
    "color": "#999"
}

###

## Delete item
DELETE http://localhost:3000/items/62c1e568a94c5762e78eacb0
